### ISSUE TITLE
Line numbering changes indentation

### ISSUE THREAD

**Issue by cconcolato** [mikemiles86/reveal-line-numbers#1]
When the code to display has more than 10 lines, if it is indented correctly in the source, the indentation gets shifted differently for lines 1-9 vs lines 9-*. I don't know if it is possible to always use 2 digits or space + 1 digit for numbers below 10.

**Comment by mikemiles86** [comment]
@cconcolato I have noticed this as well.  For CSS counters you can specify the list stye type, one of which is decimal-leading-zero. That style prefixes numbers < 10 with a zero.  

I have updated the repo to use that style by default. You can grab the latest version of the CSS from this repo, or if you just want to make the change locally then just change line 11 of line-numbers.css to be:

`content: counter(line, decimal-leading-zero);`

**Comment by AusIV** [comment]
Any chance you could add this to the readme? I spent a good amount of time looking for solutions before running across this ticket.

**Comment by mikemiles86** [comment]
I've implemented changes so that decimal-leading-zero is now part of the default output.
