### ISSUE TITLE
CSS Loaded from Wrong Location

### ISSUE THREAD

**Issue by AusIV** [mikemiles86/reveal-line-numbers#5]
The directions indicate that the line-numbers plugin should be put in the plugin/ folder, but the JavaScript attempts to load the CSS from the plugins/ folder (note the extra 's').

I had to modify the JavaScript to get the CSS to load.

**Comment by mikemiles86** [comment]
Thank you for pointing this out. There were a few PR's open about this same issue that I have merged into the project. Code should be updated and now using the correct path.
